name: Deploy to Vercel

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy to Vercel
        run: |
          npm install -g vercel
          VERCEL_TOKEN=${{ secrets.VERCEL_TOKEN }} vercel --prod --token $VERCEL_TOKEN
